/*
Generated by Yara-Rules
On 12-04-2022
*/
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2010-0805.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2010-0887.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2010-1297.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2012-0158.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2013-0074.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2013-0422.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2015-1701.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2015-2426.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2015-2545.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2015-5119.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2016-5195.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2017-11882.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2018-20250.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/cve_rules/CVE-2018-4878.yar"
