/*
Generated by Yara-Rules
On 12-04-2022
*/
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/EMAIL_Cryptowall.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/Email_PHP_Mailer.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/Email_fake_it_maintenance_bulletin.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/Email_generic_phishing.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/Email_quota_limit_warning.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/attachment.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/email_Ukraine_BE_powerattack.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/extortion_email.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/image.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/scam.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/email/urls.yar"
