/*
Generated by Yara-Rules
On 12-04-2022
*/
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_APT10_MenuPass.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_APT19_CVE-2017-0199.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_APT_OLE_JSRat.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_CVE-2017-0199.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_CVE_2017_11882.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_CVE_2017_8759.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_Contains_VBE_File.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_DDE.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_Dridex.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_Hidden_PE_file.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_MIME_ActiveMime_b64.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_PDF.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_PowerPointMouse.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_Suspicious_OLE_target.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_UserForm.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_VBA_macro_code.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_Word_2007_XML_Flat_OPC.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_hancitor_dropper.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/Maldoc_malrtf_ole2link.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/maldocs/maldoc_somerules.yar"
