/*
Generated by Yara-Rules
On 12-04-2022
*/
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/packers/JJencode.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/packers/Javascript_exploit_and_obfuscation.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/packers/packer.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/packers/packer_compiler_signatures.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/packers/peid.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/packers/tweetable-polyglot-png.yar"
