/*
Generated by Yara-Rules
On 12-04-2022
*/
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/WShell_APT_Laudanum.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/WShell_ASPXSpy.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/WShell_ChinaChopper.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/WShell_Drupalgeddon2_icos.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/WShell_PHP_Anuna.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/WShell_PHP_in_images.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/WShell_THOR_Webshells.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/Wshell_ChineseSpam.yar"
include "D:/Porcupine Project/Porcupine/antivirus/definitions/rules-master/webshells/Wshell_fire2013.yar"
